version: '3.8'

services:
  # Next.js frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/healthcare-platform
      - JWT_SECRET=${JWT_SECRET}
      - ML_API_URL=http://ml-service:5000
      - NEXT_PUBLIC_SIGNALING_SERVER_URL=http://signaling-server:3001
    depends_on:
      - mongodb
      - ml-service
      - signaling-server
    restart: always

  # MongoDB database
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  # ML service
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${ML_SECRET_KEY}
      - PORT=5000
    restart: always

  # WebRTC signaling server
  signaling-server:
    build:
      context: ./signaling-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    restart: always

volumes:
  mongodb_data:
